language: swift
osx_image: xcode9.3
xcode_project: FunctionalTableData.xcodeproj
xcode_schema: FunctionalTableDataTests
notifications:
  disabled: true
script:
  - xcodebuild test -scheme FunctionalTableData -destination "OS=11.3,name=iPhone SE" -sdk iphonesimulator11.3 | xcpretty -c
